addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.11")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "1.1.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"             % "2.5")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.1.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.3.7")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.6.1")
